# Generated by Django 6.0.7 on 2026-07-08 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_centro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=150)),
                ('tipo_programa', models.CharField(choices=[('tecnico', 'Técnico'), ('tecnologo', 'Tecnólogo')], default='tecnico', max_length=10)),
                ('id_centro_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.centro')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('num_ficha', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Número de Ficha')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('programa_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('apellidos', models.CharField(max_length=100, null=True)),
                ('num_doc', models.IntegerField(unique=True)),
                ('datos_actualizados', models.BooleanField(default=False)),
                ('resultados', models.BooleanField(default=False)),
                ('tyt', models.BooleanField(default=False)),
                ('id_ficha_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ficha')),
                ('id_rol_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.roles')),
                ('id_tipodoc_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.tipodoc')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruebas_tyt', models.BooleanField(null=True)),
                ('juicios_evaluativos', models.BooleanField(null=True)),
                ('formato_etapaproductiva', models.BooleanField(null=True)),
                ('bitacora_etapaproductiva', models.BooleanField(null=True)),
                ('actividades_bienestar', models.BooleanField(null=True)),
                ('pazysalvo_biblioteca', models.BooleanField(null=True)),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('id_aprendiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_como_aprendiz', to='mainapp.usuario')),
                ('id_instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_como_instructor', to='mainapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paz_y_salvo', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_ficha_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ficha')),
                ('id_usuario_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteCoordinacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paz_y_salvo', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_ficha_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ficha')),
                ('id_usuario_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_horas', models.PositiveIntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('id_usuario_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PrestarEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Vencido', 'Vencido')], default='Pendiente', max_length=20)),
                ('id_usuario_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_libro', models.CharField(max_length=200)),
                ('fecha_prestamo', models.DateField()),
                ('centro_formacion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_material', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo_prestamo', models.IntegerField(blank=True, help_text='Días de préstamo', null=True)),
                ('id_usuario_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoBienestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_usuario_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PazYSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_diligen', models.CharField(max_length=200)),
                ('fecha_diligen', models.DateField()),
                ('regional', models.CharField(max_length=100, null=True)),
                ('tramite', models.CharField(max_length=200, null=True)),
                ('firma_responsable', models.CharField(max_length=200, null=True)),
                ('observaciones', models.CharField(max_length=200, null=True)),
                ('firma_certificacion', models.CharField(max_length=200, null=True)),
                ('id_centro_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.centro')),
                ('id_usuario_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100, null=True)),
                ('id_usuario_FK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorxAprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitacoras_completas', models.BooleanField(default=False)),
                ('id_aprendiz_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendiz_en_seguimiento', to='mainapp.usuario')),
                ('id_instructor_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_de_seguimiento', to='mainapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ControlPazYSalvo',
            fields=[
                ('id_control', models.AutoField(primary_key=True, serialize=False)),
                ('id_ficha_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.ficha')),
                ('id_usuario_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AgEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_inicio_empresa', models.DateField(blank=True, null=True)),
                ('fecha_fin_empresa', models.DateField(blank=True, null=True)),
                ('id_aprendiz_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
            ],
        ),
    ]
